Repository Kusitms-28th-Meetup-D/frontend, pull requests merged in 2023-11, with the labels that each got.

#10 [chore] 디자인 시스템, 브레이크 포인트 설정
  package.json
  src/main.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/theme.ts
  yarn.lock
Labels: ⚙chore

#14 [feat] 추천사 페이지 객관식
  public/assets/images/recommendation/header.svg
  public/assets/images/recommendation/profile.svg
  public/assets/images/recommendation/star.svg
  src/Router.tsx
  src/components/Test.tsx
  src/components/recommendation/Keyword.tsx
  src/components/recommendation/RecommendationHeader.tsx
  src/components/recommendation/RecommendationKeywords.tsx
  src/components/recommendation/RecommendationProfile.tsx
  src/components/recommendation/RecommendationProfiles.tsx
  src/components/recommendation/RecommendationTendency.tsx
  src/components/recommendation/TendencyBox.tsx
  src/constants/KeywordList.ts
  src/constants/ProfileList.ts
  src/constants/TendencyQuestion.ts
  src/pages/recommendation/Recommendation.tsx
  src/recoil/recommendation.ts
  src/styles/theme.ts
Labels: 🛠feat

#15 [feat] 티켓 소모 후 프로필 페이지 완료
  public/assets/images/profile/quotes_close.svg
  public/assets/images/profile/quotes_open.svg
  public/assets/images/profile/range-bg.png
  public/assets/images/profile/star-leand.svg
  public/assets/images/profile/star-list-type.png
  src/Router.tsx
  src/components/header/Header.tsx
  src/components/profile/ProfileInfo.tsx
  src/components/profile/ProfileKeyword.tsx
  src/components/profile/ProfilePersonality.tsx
  src/components/profile/ProfilePersonalityContent.tsx
  src/components/profile/ProfileRecommendation.tsx
  src/components/profile/ProfileRecommendationContentsBox.tsx
  src/components/profile/ProfileSubInfo.tsx
  src/components/profile/ProfileSubInfoContent.tsx
  src/constants/KeywordList.ts
  src/constants/Profile.ts
  src/interface/Profile.ts
  src/pages/profile/Profile.tsx
Labels: 🛠feat

#16 [feat] 추천사 주관식 페이지 완료
  public/assets/images/recommendation/beforeArrow.svg
  public/assets/images/recommendation/nextArrow.svg
  src/Router.tsx
  src/components/recommendation/BeforeNextButton.tsx
  src/components/recommendation/HeroBox.tsx
  src/components/recommendation/RecommendationHero.tsx
  src/components/recommendation/RecommendationKeywords.tsx
  src/components/recommendation/RecommendationProfiles.tsx
  src/components/recommendation/RecommendationReason.tsx
  src/components/recommendation/RecommendationTendency.tsx
  src/constants/ProfileList.ts
  src/constants/TendencyQuestion.ts
  src/constants/recommendation.ts
  src/pages/recommendation/MultipleChoice.tsx
  src/pages/recommendation/Recommendation.tsx
  src/pages/recommendation/Subjective.tsx
Labels: 🛠feat

#19 [feat] 공모전 리스트 페이지 제작 완료
  public/assets/images/common/search.svg
  public/assets/images/competition/competition.svg
  public/assets/images/competition/searchBox1.svg
  public/assets/images/competition/searchBox2.svg
  src/Router.tsx
  src/components/common/Pagination.tsx
  src/components/competitionList/CompetitionBox.tsx
  src/components/competitionList/CompetitionButton.tsx
  src/components/competitionList/CompetitionListBox.tsx
  src/components/competitionList/CompetitionRecruiting.tsx
  src/components/competitionList/CompetitionSearch.tsx
  src/components/competitionList/RecruitingBox.tsx
  src/components/competitionList/SearchInput.tsx
  src/components/recommendation/BeforeNextButton.tsx
  src/components/recommendation/RecommendationHeader.tsx
  src/components/recommendation/RecommendationProfile.tsx
  src/components/recommendation/RecommendationProfiles.tsx
  src/constants/competitionList.ts
  src/pages/competitionList/CompetitionList.tsx
Labels: 🛠feat

#21 [feat] 헤더 제작 및 ★★(중요)headerState 변경 요청★★
  public/assets/images/header/header-star.svg
  src/components/header/Header.tsx
  src/components/login/KakaoLogin.tsx
  src/constants/Header.ts
  src/pages/join/Join.tsx
  src/pages/profile/Profile.tsx
  src/recoil/atom.ts
Labels: 🛠feat

#24 [feat] 결제 완료 페이지 제작
  public/assets/images/payment/paymentComplete.svg
  public/assets/images/payment/ticketCount.svg
  src/Router.tsx
  src/components/common/Button.tsx
  src/components/header/Header.tsx
  src/components/payment/Complete.tsx
  src/components/payment/PossessionTicket.tsx
  src/pages/payment/PaymentComplete.tsx
Labels: 🛠feat

#28 [feat] 티켓 충전 페이지 제작
  public/assets/images/common/leftArrow.svg
  public/assets/images/common/ticket.svg
  public/assets/images/payment/headerTicket.svg
  public/assets/images/payment/lightning.svg
  public/assets/images/payment/radioSelected.svg
  src/Router.tsx
  src/components/common/Button.tsx
  src/components/common/Title.tsx
  src/components/payment/ChargeBox.tsx
  src/components/payment/PaymentChargeBox.tsx
  src/components/payment/PaymentChargeHeader.tsx
  src/components/recommendation/RecommendationHeader.tsx
  src/constants/payment.ts
  src/pages/payment/PaymentCharge.tsx
  src/pages/payment/PaymentComplete.tsx
  src/pages/recommendation/Recommendation.tsx
Labels: 🛠feat

#37 [feat] 추천사 페이지(주관식) 디자인 수정
  src/components/recommendation/HeroBox.tsx
  src/components/recommendation/RecommendationHero.tsx
  src/components/recommendation/RecommendationReason.tsx
Labels: 🛠feat

#41 [feat] 개인 프로필 작성 페이지 제작
  src/Router.tsx
  src/components/common/BeforeNextButton.tsx
  src/components/profile/ProfileCreateBox.tsx
  src/components/profile/ProfileCreateBoxContainer.tsx
  src/components/profile/ProfileCreateHeader.tsx
  src/constants/Profile.ts
  src/pages/profile/ProfileCreate.tsx
  src/pages/recommendation/MultipleChoice.tsx
  src/pages/recommendation/Subjective.tsx
Labels: 🛠feat

#42 [feat] 공모전 상세보기 노출방식 수정 및 ★★axios api 사용시 타입 지정 방법★★
  package.json
  src/Router.tsx
  src/apis/contest/getContestInfo.ts
  src/components/contest/ContestInfo.tsx
  src/components/request/KakaoPreviewModal.tsx
  src/hooks/useContestInfo.ts
  src/interface/Contest.ts
  src/main.tsx
  src/pages/contest/Contest.tsx
  yarn.lock
Labels: 🛠feat

#50 [feat] 개인 프로필 작성 API 연동 및 모달 제작
  public/assets/images/profile/profile_create_modal.svg
  src/Router.tsx
  src/apis/axios.ts
  src/apis/competition/getCompetitionList.tsx
  src/apis/profile/postProfileCreate.ts
  src/components/common/BeforeNextButton.tsx
  src/components/competitionList/CompetitionListBox.tsx
  src/components/profile/ProfileCreateBox.tsx
  src/components/profile/ProfileCreateBoxContainer.tsx
  src/constants/Profile.ts
  src/hooks/competition/useCompetitionList.tsx
  src/hooks/profile/useProfileCreate.ts
  src/interface/Competition.ts
  src/interface/Profile.ts
  src/keys/competitionKeys.tsx
  src/pages/profile/ProfileCreate.tsx
Labels: 🔨fix, 🛠feat

#64 [feat] 내 팀 오픈하기 폼 제작
  public/assets/images/myteam/close_button.svg
  public/assets/images/myteam/complete_button.svg
  public/assets/images/myteam/form_title_circle.svg
  src/Router.tsx
  src/components/common/TwoButtonModal.tsx
  src/components/contest/ContestInfo.tsx
  src/components/myteam/ActivityAreaSelectBox.tsx
  src/components/myteam/ButtonBox.tsx
  src/components/myteam/FormTitle.tsx
  src/components/myteam/MyTeamCreateOpen.tsx
  src/components/myteam/MyTeamHeader.tsx
  src/constants/myteam.ts
  src/pages/competitionList/CompetitionList.tsx
  src/pages/myteam/MyTeam.tsx
  src/pages/myteam/MyTeamCreate.tsx
  src/pages/payment/PaymentCharge.tsx
  src/pages/profile/ProfileCreate.tsx
  src/pages/recommendation/Recommendation.tsx
Labels: 🛠feat
